"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib_even_sum(limit:int):
    """
    This function takes a limit value for the Fibonacci sequence to not exceed, then returns the sum of the even values in the sequence.
    """  
    fib_nums = [1,2]
    i = 1
    while max(fib_nums) < limit:
        fib_num = fib_nums[i] + fib_nums[i-1]
        fib_nums.append(fib_num)
        i += 1

    even_total = 0
    for num in fib_nums:
        if num % 2 == 0:
            even_total += num
    
    return even_total

print(fib_even_sum(4000000))
